export const FETCH_FACT = "FETCH_FACT";

export const FETCH_FACT_REQUESTED = "FETCH_FACT_REQUESTED";

export const FETCH_FACT_SUCCESS = "FETCH_FACT_SUCCESS";

export const FETCH_FACT_FAILURE = "FETCH_FACT_FAILURE";
